lambda_name      = "hello-java-lambda"
handler          = "Lambda::handleRequest"
runtime          = "java21"
role_name        = "lambda_exec_role"
lambda_jar_path  = "/home/llasantinelli/git-repos/aws-lambda/lambda/lambda-aws/target/lambda-aws-1.0-SNAPSHOT.jar"
